"""Sub-pixel Ken Burns moves for still images, built on ``CameraFraming``.

``ken_burns`` returns an ordinary ``Composition`` with one opaque footage layer.
Its ``Transform`` is generated by a ``CameraFraming`` rig, so the AE renderer
samples the source at fractional coordinates on every frame. Nothing snaps to
whole or even pixels, which is the jitter that integer-cropped zoompan moves
show. The rig never reveals a border: zoom and pan are clamped so the source
always covers the output.

``motion_smoothness`` and ``check_motion`` measure the result with sub-pixel
phase correlation and apply the same verdict thresholds as the NLH
``motion-check`` command.

Examples
--------
>>> import numpy as np
>>> from moviepy.ae.templates.ken_burns import KEN_BURNS_DEFAULTS, ken_burns
>>> from moviepy.ae.templates.presets import ChannelPreset
>>> preset = ChannelPreset(name="demo", size=(64, 36), fps=24, safe_margin=(4, 3))
>>> image = np.full((36, 64, 3), 128, np.uint8)
>>> comp = ken_burns(image, preset, duration=1.0, move="push", hold=0.25)
>>> comp.size, comp.duration
((64, 36), 1.0)
>>> KEN_BURNS_DEFAULTS["push_zoom"]
(1.0, 1.08)
"""

import math
import os

import numpy as np
from PIL import Image

from moviepy.ae.camera import CameraFraming
from moviepy.ae.composition import Composition
from moviepy.ae.properties.easing import Ease
from moviepy.ae.properties.keyframe import Keyframe
from moviepy.ae.templates.paper import CachedAVLayer
from moviepy.ae.templates.presets import ChannelPreset, get_preset
from moviepy.video.VideoClip import ImageClip


try:  # OpenCV is optional for import; motion measurement needs it.
    import cv2
except ImportError:  # pragma: no cover - exercised only without OpenCV
    cv2 = None


KEN_BURNS_DEFAULTS = {
    # Push dollies 8 % toward the focus. Eight percent over a 3-6 s move reads as
    # a gentle emphasis; NLH's 12 % is noticeably stronger than needed for stills.
    "push_zoom": (1.0, 1.08),
    "pull_zoom": (1.08, 1.0),
    # Pans hold 1.08x so the window has room to slide. The minimum zoom that
    # fits a 6 % pan is about 1.06, so 1.08 is never clamped on a matched aspect.
    "pan_zoom": 1.08,
    # Content slides this fraction of the output width during a pan. Small
    # enough to read as a camera drift, large enough to be visible on screen.
    "pan_distance": 0.06,
    # Subject line slightly above centre, the usual place for faces and titles.
    "focus": (0.5, 0.45),
    # Cycle order used by move="auto": push, pan right, push, pan left, pull.
    "auto_cycle": ("push", "pan-right", "push", "pan-left", "pull"),
    # Moves are eased in-out (AE easy-ease, zero speed at both ends) so the
    # motion starts and stops without a visible step.
    "easing": "easy_ease",
    # Drift = pan and push in at once, ending framed on the focus (the r2b
    # "move sideways and enlarge, settle on the main subject" camera). The window
    # travels ``drift_distance`` of the SOURCE width on each side of the middle
    # of the move, i.e. twice that in total, while zooming over ``drift_zoom``.
    # The drift moves are not in ``auto_cycle``: appending would change nothing
    # for existing indices, but inserting would, so ``auto`` stays untouched and
    # callers pick ``drift-left`` / ``drift-right`` explicitly.
    "drift_zoom": (1.02, 1.10),
    "drift_distance": 0.035,
}

MOVES = (
    "push",
    "pull",
    "pan-left",
    "pan-right",
    "pan-up",
    "pan-down",
    "drift-left",
    "drift-right",
)

# Sign of the viewing-window motion for the drift moves (+1 = window moves right).
_DRIFT = {"drift-left": -1, "drift-right": 1}

# axis (0 = x, 1 = y) and sign of the viewing-window motion. Positive x/y
# moves the window right/down, so the picture slides left/up.
_PAN = {
    "pan-left": (0, -1),
    "pan-right": (0, 1),
    "pan-up": (1, -1),
    "pan-down": (1, 1),
}

# NLH motion-check thresholds, unchanged. Displacements are expressed in
# pixels of a 1920-wide frame, as NLH reports them for 1080p output.
_REFERENCE_WIDTH = 1920
_STILL_PX = 0.05
_JERK_FLOOR_PX = 0.6
_SMOOTH_STILL_RATIO = 0.2
_SMOOTH_JERK_RATIO = 0.05
_STATIC_JERK_RATIO = 0.02
# Mean-removed crops whose largest deviation stays below this (8-bit codes) are
# treated as featureless.
_FLAT_LEVEL = 0.5


def _finite(value, name, low=None, *, strict=False):
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        raise TypeError(f"{name} must be a real number")
    value = float(value)
    if not math.isfinite(value):
        raise ValueError(f"{name} must be finite")
    if low is not None and (value <= low if strict else value < low):
        bound = ">" if strict else ">="
        raise ValueError(f"{name} must be {bound} {low}")
    return value


def _source_array(image):
    """Return an opaque ``(h, w, 3)`` uint8 RGB array from a path, array or clip."""
    if isinstance(image, ImageClip):
        frame = np.asarray(image.get_frame(0))
        if frame.dtype != np.uint8:
            raise TypeError("ImageClip frames must be uint8")
    elif isinstance(image, (str, os.PathLike)):
        with Image.open(image) as pil:
            if pil.mode in ("RGBA", "LA", "P") or "transparency" in pil.info:
                rgba = np.asarray(pil.convert("RGBA"))
                if rgba[..., 3].min() < 255:
                    raise ValueError("ken_burns needs an opaque image")
                frame = rgba[..., :3].copy()
            else:
                frame = np.asarray(pil.convert("RGB"))
    else:
        frame = np.asarray(image)
        if frame.dtype != np.uint8:
            raise TypeError("image arrays must be uint8")
        if frame.ndim == 2:
            frame = np.repeat(frame[..., None], 3, axis=2)
        elif frame.ndim == 3 and frame.shape[2] == 4:
            if frame[..., 3].min() < 255:
                raise ValueError("ken_burns needs an opaque image")
            frame = frame[..., :3]
        if frame.ndim != 3 or frame.shape[2] != 3:
            raise ValueError("image must be (h, w), (h, w, 3) or (h, w, 4)")
    frame = np.ascontiguousarray(frame[..., :3])
    if min(frame.shape[:2]) < 2:
        raise ValueError("image must be at least 2x2 pixels")
    return frame


def _resolve_move(move, index):
    if move == "auto":
        cycle = KEN_BURNS_DEFAULTS["auto_cycle"]
        return cycle[int(index) % len(cycle)]
    if move not in MOVES:
        raise ValueError(f"move must be auto or one of {MOVES}")
    return move


def _zoom_pair(zoom, default):
    if zoom is None:
        return tuple(default)
    if isinstance(zoom, (tuple, list)):
        if len(zoom) != 2:
            raise ValueError("zoom pair requires start and end factors")
        pair = tuple(_finite(v, "zoom", 1.0) for v in zoom)
        return pair
    value = _finite(zoom, "zoom", 1.0)
    return (value, value)


def ken_burns(
    image,
    preset,
    *,
    duration,
    move="auto",
    index=0,
    zoom=None,
    focus=None,
    distance=None,
    hold=None,
    lead=0.0,
    easing=None,
    segment=(0.0, 1.0),
):
    """Return a Composition that moves across one still image.

    Parameters
    ----------
    image : str, os.PathLike, numpy.ndarray or ImageClip
        Opaque RGB(A) source. Transparent pixels raise ``ValueError``.
    preset : ChannelPreset or str
        Supplies the output ``size``, ``fps`` and default ``hold``.
    duration : float
        Composition length in seconds.
    move : str
        ``"push"``, ``"pull"``, ``"pan-left"``, ``"pan-right"``, ``"pan-up"``,
        ``"pan-down"``, ``"drift-left"``, ``"drift-right"`` or ``"auto"``
        (cycles through the auto order by ``index``; the drift moves are not part
        of that cycle). A drift pans horizontally while pushing in and ends
        framed on ``focus``, then holds that framing for ``hold`` seconds.
    index : int
        Position in the auto cycle; ignored unless ``move="auto"``.
    zoom : float or (float, float), optional
        Zoom relative to cover, at least 1. Push and pull take a pair; pans take
        one value. Drift takes a pair (default ``drift_zoom``). Defaults come
        from ``KEN_BURNS_DEFAULTS``.
    focus : (float, float), optional
        Subject point as fractions of the source width and height.
    distance : float, optional
        Pan travel as a fraction of the output width (pans). For drifts it is
        the half-travel as a fraction of the source width (default 0.035).
    hold : float, optional
        Seconds at the end that keep the final framing. Defaults to
        ``preset.hold``.
    lead : float
        Seconds of stillness before the move starts.
    easing : Ease, optional
        Curve for the move. Defaults to AE easy-ease (in-out).
    segment : (float, float)
        Drift only. The part ``(a, b)`` of the whole move, as fractions of its
        eased progress, that this shot shows. Consecutive shots of one still use
        ``(0, .5)`` then ``(.5, 1)`` to continue a single move without a seam:
        the first ends exactly where the second starts. Default ``(0, 1)``.

    Returns
    -------
    Composition
        One footage layer, ``comp.layers[0]``. The ``CameraFraming`` rig that
        drives its transform is ``comp.framing``. Edit that rig's ``focus``,
        ``pan`` or ``zoom`` to keyframe the move while keeping the no-border
        guarantee.

    Raises
    ------
    ValueError
        For an unknown move, a non-opaque image, or timing or zoom that cannot
        be honoured without revealing a border.

    Examples
    --------
    >>> import numpy as np
    >>> from moviepy.ae.templates.presets import ChannelPreset
    >>> preset = ChannelPreset(name="doc", size=(32, 18), fps=24, safe_margin=(2, 2))
    >>> comp = ken_burns(np.zeros((18, 32, 3), np.uint8), preset, duration=0.5,
    ...                  move="pan-right", hold=0.1)
    >>> comp.framing.pan is not None, len(comp.layers)
    (True, 1)
    """
    if isinstance(preset, str):
        preset = get_preset(preset)
    if not isinstance(preset, ChannelPreset):
        raise TypeError("preset must be a ChannelPreset or a preset name")
    duration = _finite(duration, "duration", 0, strict=True)
    lead = _finite(lead, "lead", 0)
    hold = preset.hold if hold is None else _finite(hold, "hold", 0)
    t0, t1 = lead, duration - hold
    if t1 <= t0:
        raise ValueError("duration must exceed lead plus hold")
    move = _resolve_move(move, index)
    seg_a, seg_b = (_finite(v, "segment", 0) for v in segment)
    if not 0 <= seg_a < seg_b <= 1:
        raise ValueError("segment must satisfy 0 <= a < b <= 1")
    if (seg_a, seg_b) != (0.0, 1.0) and move not in _DRIFT:
        raise ValueError("segment applies to drift moves only")
    ease = Ease.easy_ease() if easing is None else easing
    if not isinstance(ease, Ease):
        raise TypeError("easing must be an Ease")
    source = _source_array(image)
    ih, iw = source.shape[:2]
    width, height = preset.size
    fx, fy = KEN_BURNS_DEFAULTS["focus"] if focus is None else focus
    fx, fy = _finite(fx, "focus x", 0), _finite(fy, "focus y", 0)
    if fx > 1 or fy > 1:
        raise ValueError("focus fractions must lie in [0, 1]")
    focus_px = (fx * (iw - 1), fy * (ih - 1))

    if move in _DRIFT:
        z0, z1 = _zoom_pair(zoom, KEN_BURNS_DEFAULTS["drift_zoom"])
        half = KEN_BURNS_DEFAULTS["drift_distance"]
        if distance is not None:
            half = _finite(distance, "distance", 0, strict=True)
        if half > 0.5:
            raise ValueError("drift distance is a fraction of width and must be <= 0.5")
        # Window centre x at progress p: it arrives on the focus at p = 1 having
        # slid ``2 * half`` of the source width, so p = 0.5 is the middle of the
        # travel as in r2b. CameraFraming clamps it so no border ever shows.
        shift = _DRIFT[move] * 2 * half * iw

        def reachable(z, point):
            # Nearest centre the rig can honour at constant zoom ``z``.
            probe = CameraFraming((iw, ih), (width, height), overscan=1.0, zoom=z)
            probe.focus = point
            return probe.sample(0).center

        # The reachable window grows with zoom, so clamping both ends once keeps
        # the straight path between them inside the limits at every zoom in
        # between (the bounds are convex/concave in zoom). The rig therefore
        # never clips mid-move, which would show up as a kink in the speed.
        end_c = reachable(z1, focus_px)
        start_c = reachable(z0, (end_c[0] - shift, end_c[1]))

        def at(p):
            return (
                z0 + (z1 - z0) * p,
                (
                    start_c[0] + (end_c[0] - start_c[0]) * p,
                    start_c[1] + (end_c[1] - start_c[1]) * p,
                ),
            )

        if (seg_a, seg_b) == (0.0, 1.0):
            (za, ca), (zb, cb) = at(0.0), at(1.0)
            zoom_keys = [Keyframe(t0, za, out_ease=ease), Keyframe(t1, zb)]
            focus_keys = [Keyframe(t0, ca, out_ease=ease), Keyframe(t1, cb)]
        else:
            # Sample the globally eased curve once per frame so adjoining segments
            # share their boundary value and speed.
            count = max(2, int(math.ceil((t1 - t0) * preset.fps)) + 1)
            zoom_keys, focus_keys = [], []
            for k in range(count):
                u = k / (count - 1)
                t = t0 + (t1 - t0) * u
                zk, ck = at(ease(seg_a + (seg_b - seg_a) * u))
                zoom_keys.append(Keyframe(t, zk))
                focus_keys.append(Keyframe(t, ck))
        framing = CameraFraming(
            (iw, ih),
            (width, height),
            overscan=1.0,
            zoom=zoom_keys,
            focus=focus_keys,
        )
    elif move in ("push", "pull"):
        if distance is not None:
            raise ValueError("distance applies to pan moves only")
        default = KEN_BURNS_DEFAULTS["push_zoom" if move == "push" else "pull_zoom"]
        z0, z1 = _zoom_pair(zoom, default)
        zmax = max(z0, z1)

        def centre_at(z):
            # Linear in zoom, so the focus eases with the same curve as the zoom.
            k = 0.0 if zmax <= 1 else min(1.0, max(0.0, (z - 1) / (zmax - 1)))
            cx, cy = (iw - 1) / 2, (ih - 1) / 2
            return (
                cx + k * (focus_px[0] - cx),
                cy + k * (focus_px[1] - cy),
            )

        framing = CameraFraming(
            (iw, ih),
            (width, height),
            overscan=1.0,
            zoom=[Keyframe(t0, z0, out_ease=ease), Keyframe(t1, z1)],
            focus=[
                Keyframe(t0, centre_at(z0), out_ease=ease),
                Keyframe(t1, centre_at(z1)),
            ],
        )
    else:
        distance_frac = KEN_BURNS_DEFAULTS["pan_distance"]
        if distance is not None:
            distance_frac = _finite(distance, "distance", 0, strict=True)
        if distance_frac > 1:
            raise ValueError("distance is a fraction of width and must be <= 1")
        travel = distance_frac * width  # output pixels the content slides
        axis, sign = _PAN[move]
        spans = (width - 1, height - 1)
        extent = (iw - 1, ih - 1)
        if min(extent) < 1:
            raise ValueError("image must be at least 2x2 pixels")
        cover = max(spans[0] / extent[0], spans[1] / extent[1])
        # The window spans spans/scale source pixels and must leave room for
        # travel/scale of slide, so extent * scale >= spans + travel. The 0.5 %
        # margin absorbs the guard band CameraFraming reserves at the edges.
        needed = (spans[axis] + travel) / (extent[axis] * cover) * 1.005
        if zoom is None:
            z = max(KEN_BURNS_DEFAULTS["pan_zoom"], needed)
        else:
            z0, z1 = _zoom_pair(zoom, None)
            if z0 != z1:
                raise ValueError("pan moves take one zoom value")
            z = z0
            if z < needed:
                raise ValueError(
                    f"zoom {z:g} too small for a pan of {distance_frac:g} "
                    f"width; need at least {needed:.4f}"
                )
        probe = CameraFraming((iw, ih), (width, height), overscan=1.0, zoom=z)
        scale = probe.sample(0).scale
        step = travel / scale  # source pixels of window travel
        # Read the exact reachable centre range from the rig itself: a focus far
        # outside the source is clamped to the limit, which includes its guard band.
        probe.focus = (-1e6, -1e6)
        lowest = probe.sample(0).center[axis]
        probe.focus = (1e6, 1e6)
        highest = probe.sample(0).center[axis]
        if highest - lowest < step - 1e-9:
            raise ValueError("pan distance does not fit inside the source")
        mid = min(max(focus_px[axis], lowest + step / 2), highest - step / 2)
        start, end = list(focus_px), list(focus_px)
        start[axis] = mid - sign * step / 2
        end[axis] = mid + sign * step / 2
        framing = CameraFraming(
            (iw, ih),
            (width, height),
            overscan=1.0,
            zoom=z,
            focus=[
                Keyframe(t0, tuple(start), out_ease=ease),
                Keyframe(t1, tuple(end)),
            ],
        )

    comp = Composition(
        size=(width, height), fps=preset.fps, duration=duration, transparent=False
    )
    clip = ImageClip(source, transparent=False).with_duration(duration)
    # The still never changes: import it into the renderer once, not per frame.
    comp.add_layer(CachedAVLayer(clip, transform=framing.to_transform()))
    comp.framing = framing
    return comp


def _gray(frame):
    arr = np.asarray(frame, np.float32)
    if arr.ndim == 3:
        arr = arr[..., :3] @ np.array([0.299, 0.587, 0.114], np.float32)
    return arr


def motion_smoothness(frames, *, box=None):
    """Measure per-frame displacement and classify the motion.

    Parameters
    ----------
    frames : iterable of arrays
        Consecutive frames, ``(h, w, 3)`` RGB or ``(h, w)`` gray, all the same
        shape.
    box : (int, int, int, int), optional
        Pixel region ``(x0, y0, x1, y1)`` to track. Defaults to the whole frame:
        a full-frame window has the most texture, so it is the least noisy at
        small sizes. NLH used a top-left box, which is noisier here.

    Returns
    -------
    dict
        ``displacement`` (per-step shift, in 1920-wide pixels), ``median``,
        ``still_ratio``, ``jerk_ratio``, ``max_jerk`` (largest change between
        consecutive steps), and ``verdict`` (``"SMOOTH"``, ``"STATIC"`` or
        ``"JITTER"``).

    Notes
    -----
    Shifts come from ``cv2.phaseCorrelate`` on a mean-removed Hanning window,
    so they are sub-pixel. Verdicts use NLH's thresholds: SMOOTH when fewer
    than 20 % of steps are still and fewer than 5 % spike; STATIC when the
    median is near zero and there are almost no spikes; otherwise JITTER.

    Examples
    --------
    >>> import numpy as np
    >>> frame = np.random.default_rng(0).integers(0, 255, (32, 64), np.uint8)
    >>> motion_smoothness([frame, frame, frame])["verdict"]
    'STATIC'
    """
    if cv2 is None:  # pragma: no cover
        raise RuntimeError("motion_smoothness requires OpenCV (cv2)")
    grays = [_gray(f) for f in frames]
    if len(grays) < 2:
        raise ValueError("motion_smoothness needs at least two frames")
    height, width = grays[0].shape
    if any(g.shape != (height, width) for g in grays):
        raise ValueError("all frames must share one shape")
    x0, y0, x1, y1 = (0, 0, width, height) if box is None else box
    if not (0 <= x0 < x1 <= width and 0 <= y0 < y1 <= height):
        raise ValueError("box must lie inside the frame")
    window = cv2.createHanningWindow((x1 - x0, y1 - y0), cv2.CV_32F)
    crops = []
    for gray in grays:
        patch = np.ascontiguousarray(gray[y0:y1, x0:x1])
        crops.append(patch - patch.mean())
    scale = _REFERENCE_WIDTH / width
    shifts = []
    flat = [float(np.abs(c).max()) < _FLAT_LEVEL for c in crops]
    for k, (prev, cur) in enumerate(zip(crops[:-1], crops[1:])):
        if flat[k] or flat[k + 1]:
            # A featureless crop (blank, black or a solid colour) has no phase:
            # phaseCorrelate would return an arbitrary huge shift. No texture, no
            # measurable motion.
            shifts.append(0.0)
            continue
        # phaseCorrelate may write into its inputs, so each pair gets copies.
        (dx, dy), _ = cv2.phaseCorrelate(prev.copy(), cur.copy(), window)
        shifts.append(math.hypot(dx, dy) * scale)
    steps = np.asarray(shifts, np.float64)
    median = float(np.median(steps))
    still = float((steps < _STILL_PX).mean())
    jerk = float((steps > max(_JERK_FLOOR_PX, 3 * median)).mean())
    max_jerk = float(np.max(np.abs(np.diff(steps)))) if len(steps) > 1 else 0.0
    if still < _SMOOTH_STILL_RATIO and jerk < _SMOOTH_JERK_RATIO:
        verdict = "SMOOTH"
    elif median < _STILL_PX and jerk < _STATIC_JERK_RATIO:
        verdict = "STATIC"
    else:
        verdict = "JITTER"
    return {
        "frames": len(grays),
        "displacement": [round(float(v), 3) for v in steps],
        "median": round(median, 3),
        "still_ratio": round(still, 3),
        "jerk_ratio": round(jerk, 3),
        "max_jerk": round(max_jerk, 3),
        "verdict": verdict,
    }


def check_motion(clip_or_comp, start, duration, *, box=None):
    """Sample frames from any clip or Composition and run ``motion_smoothness``.

    Parameters
    ----------
    clip_or_comp : VideoClip or Composition
        Anything with ``get_frame(t)`` and an ``fps`` attribute.
    start : float
        First sampled time in seconds.
    duration : float
        Span to sample, in seconds. Frames are taken at the clip's fps.
    box : (int, int, int, int), optional
        Tracking region, passed to ``motion_smoothness``.

    Returns
    -------
    dict
        The ``motion_smoothness`` result, with ``start`` and ``duration`` added.

    Examples
    --------
    >>> import numpy as np
    >>> from moviepy import ImageClip
    >>> noise = np.random.default_rng(0).integers(0, 255, (16, 16, 3), np.uint8)
    >>> clip = ImageClip(noise).with_duration(1)
    >>> clip.fps = 4
    >>> check_motion(clip, 0, 1)["verdict"]
    'STATIC'
    """
    fps = float(getattr(clip_or_comp, "fps", None) or 24.0)
    count = max(2, int(round(_finite(duration, "duration", 0, strict=True) * fps)))
    start = _finite(start, "start", 0)
    times = start + np.arange(count) / fps
    end = getattr(clip_or_comp, "duration", None)
    if isinstance(end, (int, float)) and math.isfinite(end) and end > 0:
        # A Composition renders nothing at or past its end; hold the last frame
        # like the AE footage layers do instead of measuring blank frames.
        times = np.minimum(times, math.nextafter(float(end), 0.0))
    frames = [np.asarray(clip_or_comp.get_frame(float(t))) for t in times]
    result = motion_smoothness(frames, box=box)
    result["start"] = start
    result["duration"] = float(duration)
    return result
